# to create this environment file run `conda env create -f environment.yaml` in terminal
# to activate this environment run `conda activate plane_spotter`
name: 'plane_spotter'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip:
    - requests==2.31.0